# Generated by Django 3.1.2 on 2020-10-30 11:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиент',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ф.И.О.')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('city', models.CharField(max_length=255, verbose_name='Страна, Город')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('desired_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Желаемый бюджет')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок разработки')),
                ('discount_subscription', models.BooleanField(blank=True, default=False, verbose_name='Подписка на скидки')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientProfile', to='client.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
    ]
