# Generated by Django 3.1.3 on 2020-11-07 15:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import task.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания проекта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления проекта')),
                ('deadline', models.DateField(validators=[django.core.validators.MinValueValidator(task.utils.get_today)], verbose_name='Дата сдачи проекта')),
                ('status', models.CharField(choices=[('DV', 'Developing'), ('CM', 'Completed'), ('SS', 'Suspended')], default='DV', max_length=2, verbose_name='Статус проекта')),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='client.client', verbose_name='Заказчик')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='manager.manager', verbose_name='Ответсвенный менеджер')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['deadline', 'created_at', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задания')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подзадачи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнена ли подзадача')),
                ('description', models.TextField(verbose_name='Описание')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
            },
        ),
    ]
